<!DOCTYPE html>
<html lang="en">

<head>
    <title>
        <?=$title; ?>
    </title>
</head>

<body>
    <h1><?=$title; ?></h1>
<?php include __DIR__ . '/nav.phtml'; ?>
    <table>
    <tr>
       <th>ID</th>
       <th>Name</th>
       <th>Email</th>
    </tr>
    <tr>
       <td><?=$user['id']; ?></td>
       <td><?=$user['username']; ?></td>
       <td><?=$user['email']; ?></td>
    </tr>
    </table>

</body>

</html>
